#!/usr/bin/env bash

ps cax | grep yabai > /dev/null
if [ $? -eq 0 ]; then
  /usr/local/bin/yabai -m query --spaces --space | grep index | cut -f2- -d: | cut -d',' -f1
  # currentSpaceIndex=$(/usr/local/bin/yabai -m query --spaces --space | grep index | cut -f2- -d: | cut -d',' -f1)
  # displayIndex=$(/usr/local/bin/yabai -m query --spaces --space | grep display | cut -f2- -d: | cut -d',' -f1)
  # spacesForDisplay=$(/usr/local/bin/yabai -m query --displays --display  | /usr/local/bin/jq -r '.spaces | tostring')
  # echo Display: ${displayIndex}: Space: ${currentSpaceIndex} Spaces: ${spacesForDisplay}
else
	ps cax | grep chunkwm > /dev/null
	if [ $? -eq 0 ]; then
	  /usr/local/bin/chunkc tiling::query --desktop id
	else
		echo ""
	fi
fi

